PREFIX uni: <http://www.example.org/university#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?teacher ?age
WHERE {
  ?teacher rdf:type uni:Teacher ;
           uni:hasName "Alice" ;
           uni:hasAge ?age .
}